window {
    gap = 5
    padding = 5
}
#this will be ingnored

container{
    gap = 5
    # this will be ingnored
    padding=5
}

binds {
    mod + ESC = exit
    mod + C = exec(kitty)
    mod + H = cycle_toplevel
    mod + F = change_container
    mod + V = create_vertical_container
    mod + H = create_horizontal_container
}

