window {
    gap = 5
    padding = 5

    border {
        true,
        size(5, 5, 5, 5),
        rgba(100, 175, 20, 255)
    }
}
#this will be ingnored

container{
    gap = 5
    # this will be ingnored
    padding=5

    border {
        true,
        size(2, 2, 2, 2),
        rgba(100, 0, 20, 255)
    }
}

binds {
    ESC = mod

    mod + ESC = exit
    mod + C = exec(kitty)
    mod + L = cycle_toplevel
    mod + F = change_container
    mod + V = create_vertical_container
    mod + H = create_horizontal_container
}

